### ISSUE TITLE
 Unexpected token (632:27) while parsing. When I use the command to generate the anchor-browserified.js

### ISSUE THREAD

**Issue by OniMock** [ImGroovin/Lab-Assistant#1]
Hello,
Thanks for the project

When I run the command `browserify anchor-input.js --standalone BrowserScore -p esmify --exclude process -o anchor-browserified.js`

I get this error:

> SyntaxError: Unexpected token (632:27) while parsing C:\myProject\SageLabs\node_modules\@solana\web3.js\lib\index.browser.cjs.js while parsing file: C:\myProject\SageLabs\node_modules\@solana\web3.js\lib\index.browser.cjs.js
    at DestroyableTransform.end [as _flush] (C:\Users\onimock\AppData\Roaming\npm\node_modules\browserify\node_modules\insert-module-globals\index.js:114:21)
    at DestroyableTransform.prefinish (C:\Users\onimock\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at DestroyableTransform.emit (node:events:514:28)
    at prefinish (C:\Users\onimock\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (C:\Users\onimock\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (C:\Users\onimock\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at Writable.end (C:\Users\onimock\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:594:22)
    at DuplexWrapper.onend (C:\myProject\SageLabs\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:628:28)
    at DuplexWrapper.emit (node:events:526:35)
    at endReadableNT (C:\myProject\SageLabs\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Do you have any idea what it could be?

I have already installed all dependencies, and create the files anchor-input.js and buffer-input.js
The file bs58.bundle.js I managed to generate it without any problems.

**Comment by edilvolima** [comment]
I have the same problem. I had to install all the dependencies manually and after running it returns the same error as the friend above.

> 

$ browserify node_modules/bs58/index.js -o bs58.bundle.js --standalone bs58

$ browserify anchor-input.js --standalone BrowserScore -p esmify --exclude process -o anchor-browserified.js
SyntaxError: Unexpected token (632:27) while parsing /home/vm/Dev/test/node_modules/@solana/web3.js/lib/index.browser.cjs.js while parsing file: /home/vm/Dev/test/node_modules/@solana/web3.js/lib/index.browser.cjs.js
    at DestroyableTransform.end [as _flush] (/usr/local/lib/node_modules/browserify/node_modules/insert-module-globals/index.js:114:21)
    at DestroyableTransform.prefinish (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (node:events:513:28)
    at prefinish (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at Writable.end (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:594:22)
    at DuplexWrapper.onend (/home/vm/Dev/test/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:627:28)
    at DuplexWrapper.emit (node:events:525:35)
    at endReadableNT (/home/vm/Dev/test/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
